name: "productCount"
request:
    url: /api/productCount
    method: GET
    headers:
      storehub-business: ${ENV(STOREHUB_BUSINESS)}
      storehub-registerId: ${ENV(STOREHUB_REGISTERID)}
      storehub-token: ${ENV(STOREHUB_TOKEN )}
